apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.container.environment.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.container.environment.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.container.environment.POSTGRES_PASSWORD }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.container.environment.KEYCLOAK_DB_PASSWORD }}
  API_DB_PASSWORD: {{ .Values.container.environment.API_DB_PASSWORD }}