apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.container.environment.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.container.environment.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.container.environment.POSTGRES_PASSWORD }}