apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  type: {{ .Values.container.service.type }}
  ports:
    - port: {{ .Values.container.service.port }}
      targetPort: {{ .Values.container.service.targetPort }}
      protocol: TCP