apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: people-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: people.mcqueide.com
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: people-keycloak-keycloak
            port:
              number: 8080
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: people-api
            port:
              number: 8081
      - path: /api-docs
        pathType: Prefix
        backend:
          service:
            name: people-api
            port:
              number: 8081
      - path: /actuator
        pathType: Prefix
        backend:
          service:
            name: people-api
            port:
              number: 8081
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: people-api
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: people-frontend
            port:
              number: 3000
  tls:
  - hosts:
    - people.mcqueide.com
    secretName: letsencrypt-tls