name: CI

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: mcqueide
  IMAGE_NAME: mcqueide/people-api
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  ci:

    runs-on: ubuntu-latest
    permissions:
      contents: read # Ler o conteúdo do repositório
      packages: write # Permitir publicar pacotes no GitHub Packages
      pull-requests: write # Permitir criar e atualizar pull requests
      security-events: write # Enviar eventos de segurança para o Github Security
      id-token: write # Permitir emitir tokens OIDC para autenticação com provedores externos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build for CI
        id: build-ci
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true # driver docker-container
          target: ci
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build for analysis
        id: build-for-analysis
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Analyze for critical and high CVEs
        id: docker-scout-cves
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHA }}
          only-severities: critical,high
          only-fixed: true
          summary: true # publicar github actions e pull request
          exit-code: true

      - name: Analyze for all CVEs
        id: docker-scout-all-cves
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHA }}
          summary: true
          sarif-file: sarif.output.json

      # # Se o repositório for público, é possível testar este recurso, caso contrário somente com organização ativa
      - name: Upload SARIF result
        id: upload-sarif
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif.output.json